### ISSUE TITLE
TypeError: W_init() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by kazzastic** [sorenbouma/keras-oneshot#20]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-7674879a3fe6> in <module>
     29 convnet = Sequential()
     30 convnet.add(Conv2D(64,(10,10),activation='relu',input_shape=input_shape,
---> 31                    kernel_initializer=W_init,kernel_regularizer=l2(2e-4)))
     32 convnet.add(MaxPooling2D())
     33 convnet.add(Conv2D(128,(7,7),activation='relu',

~/anaconda3/lib/python3.7/site-packages/keras/engine/sequential.py in add(self, layer)
    164                     # and create the node connecting the current layer
    165                     # to the input layer we just created.
--> 166                     layer(x)
    167                     set_inputs = True
    168             else:

~/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    423                                          'You can build it manually via: '
    424                                          '`layer.build(batch_input_shape)`')
--> 425                 self.build(unpack_singleton(input_shapes))
    426                 self.built = True
    427 

~/anaconda3/lib/python3.7/site-packages/keras/layers/convolutional.py in build(self, input_shape)
    139                                       name='kernel',
    140                                       regularizer=self.kernel_regularizer,
--> 141                                       constraint=self.kernel_constraint)
    142         if self.use_bias:
    143             self.bias = self.add_weight(shape=(self.filters,),

~/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py in add_weight(self, name, shape, dtype, initializer, regularizer, trainable, constraint)
    241         if dtype is None:
    242             dtype = self.dtype
--> 243         weight = K.variable(initializer(shape, dtype=dtype),
    244                             dtype=dtype,
    245                             name=name,

**TypeError: W_init() got an unexpected keyword argument 'dtype'**

How can I solve this error?

**Comment by StefanLyj** [comment]
Have you solved this problem?I have the same problem

**Comment by kazzastic** [comment]
> Have you solved this problem?I have the same problem

I have not, sorry.

**Comment by StefanLyj** [comment]
I had search in   "https://keras-cn.readthedocs.io/en/latest/other/initializations/#_1" ,modify ----

-def W_init(shape,name=None):
+def W_init(shape,dtype=None):
    """Initialize weights as in paper"""
    values = rng.normal(loc=0,scale=1e-2,size=shape)
- return K.variable(values,name=name)
+    return K.variable(values,dtype=dtype)
#//TODO: figure out how to initialize layer biases in keras.
-def b_init(shape,name=None):
+def b_init(shape,dtype=None):
    """Initialize bias as in paper"""
    values=rng.normal(loc=0.5,scale=1e-2,size=shape)
- return K.variable(values,name=name)
+    return K.variable(values,dtype=dtype)

error  gone，maybe it has work。

**Comment by kazzastic** [comment]
I am sorry, but I can;t test this since I have moved on with my research work on such NN, I am going to close this issue since it has no use for me anymore.

**Comment by Spidy20** [comment]
You can use the below function for the same. The changes are just of dtype.

`def W_init(shape,dtype=None):
    """Initialize weights as in paper"""
    values = np.random.normal(loc=0,scale=1e-2,size=shape)
    return K.variable(values,dtype=dtype)`
