### ISSUE TITLE
name 'best' is not defined

### ISSUE THREAD

**Issue by rawmean** [sorenbouma/keras-oneshot#5]
Another problem:

    for i in range(0,1000):
    print (i)
    (inputs,targets)=loader.get_batch(batch_size)
    loss=siamese_net.train_on_batch(inputs,targets)
    if i % evaluate_every == 0:
        val_acc = loader.test_oneshot(siamese_net,N_way,n_val,verbose=True)
        if val_acc >= best:  #<-- best is used before it is initialized
            print("saving")
            siamese_net.save('./weights')
            best=val_acc

**Comment by sorenbouma** [comment]
my bad, fixed.

**Comment by vfdev-5** [comment]
With initialization `best=9999` the code to save the model `siamese_net.save(weights_path)` is never called.
